name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

    - name: Run Custom Tests
      run: |
        cd test
        g++ -o extractData_test ./extractData_test.cpp
        ./extractData_test
