name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: iron

    - name: Install dependencies
      run: |
        sudo apt update
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro iron -y

    - name: Build
      run: colcon build --symlink-install

    - name: Test
      run: colcon test && colcon test-result --verbose